@startuml

title __REQUESTS's Class Diagram__\n

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestAssetType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestBooleanType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestClassType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestColorType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestEnumType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestFloatType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestIntegerType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestListType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestQuaternionType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestStringType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestVec2fType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestVec2iType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestVec3fType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestVect3iType {
              + action()
              + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          interface helron.foundationwizard.com.ui.requests.Requestable {
              {abstract} + action()
              {abstract} + isRequired()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestsGenerator {
              ~ requestsList : List<Requestable>
              + RequestsGenerator()
              + getRequestsList()
          }
        }
      }
    }
  }
  

  helron.foundationwizard.com.ui.requests.RequestAssetType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestBooleanType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestClassType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestColorType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestEnumType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestFloatType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestIntegerType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestListType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestQuaternionType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestStringType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestVec2fType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestVec2iType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestVec3fType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestVect3iType .up.|> helron.foundationwizard.com.ui.requests.Requestable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
