@startuml

title __WIZZARD's Class Diagram__\n

  namespace  {
    namespace elron.foundationwizard.com {
      class helron.foundationwizard.com.Main {
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace api {
        class helron.foundationwizard.com.api.ApiStructuresExtractor {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace api {
        class helron.foundationwizard.com.api.LuaGenerator {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace datagenerator {
        class helron.foundationwizard.com.datagenerator.DataStructure {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace datagenerator {
        class helron.foundationwizard.com.datagenerator.DataStructureAsset {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace datagenerator {
        class helron.foundationwizard.com.datagenerator.DataStructureClass {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace datagenerator {
        class helron.foundationwizard.com.datagenerator.DataStructureEnum {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace datagenerator {
        class helron.foundationwizard.com.datagenerator.DataStructureMap {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace datagenerator {
        class helron.foundationwizard.com.datagenerator.DataStructureMapGenerator {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace datagenerator {
        class helron.foundationwizard.com.datagenerator.DataStructureStruct {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace datagenerator {
        enum DataStructureType {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace datagenerator {
        enum ParamType {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace datagenerator {
        class helron.foundationwizard.com.datagenerator.Parameter {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ihm {
        enum FieldType {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ihm {
        class helron.foundationwizard.com.ihm.FormField {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ihm {
        abstract class helron.foundationwizard.com.ihm.FormRequestDialog {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ihm {
        class helron.foundationwizard.com.ihm.FormRow {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ihm {
        class helron.foundationwizard.com.ihm.FoundationAPI {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ihm {
        class helron.foundationwizard.com.ihm.LuaScriptFrame {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ihm {
        class helron.foundationwizard.com.ihm.MainFrame {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        class helron.foundationwizard.com.ui.FormCLass {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        interface helron.foundationwizard.com.ui.FormSelector {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        enum FormType {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        class helron.foundationwizard.com.ui.FormsContainer {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        class helron.foundationwizard.com.ui.Home {
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace customcomponents {
          class helron.foundationwizard.com.ui.customcomponents.JImagePanel {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace customcomponents {
          class helron.foundationwizard.com.ui.customcomponents.JTextFieldLink {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace customcomponents {
          class helron.foundationwizard.com.ui.customcomponents.JtextFileChooser {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace customcomponents {
          class helron.foundationwizard.com.ui.customcomponents.ListenedJCheckBox {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace customcomponents {
          class helron.foundationwizard.com.ui.customcomponents.ListenedJComboBox {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace customcomponents {
          class helron.foundationwizard.com.ui.customcomponents.ListenedJList {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace customcomponents {
          class helron.foundationwizard.com.ui.customcomponents.ListenedJSpinner {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace customcomponents {
          class helron.foundationwizard.com.ui.customcomponents.ListenedTextField {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace customcomponents {
          class helron.foundationwizard.com.ui.customcomponents.PlusButton {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace customcomponents {
          class helron.foundationwizard.com.ui.customcomponents.ValidateButton {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestAssetType {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestBooleanType {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestClassType {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestEnumType {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestIntegerType {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestListType {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestStringType {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          interface helron.foundationwizard.com.ui.requests.Requestable {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace elron.foundationwizard.com {
      namespace ui {
        namespace requests {
          class helron.foundationwizard.com.ui.requests.RequestsGenerator {
          }
        }
      }
    }
  }
  

  helron.foundationwizard.com.datagenerator.DataStructure o-- helron.foundationwizard.com.datagenerator.DataStructureType : dataStructureType
  helron.foundationwizard.com.datagenerator.DataStructureAsset -up-|> helron.foundationwizard.com.datagenerator.DataStructure
  helron.foundationwizard.com.datagenerator.DataStructureClass -up-|> helron.foundationwizard.com.datagenerator.DataStructure
  helron.foundationwizard.com.datagenerator.DataStructureEnum -up-|> helron.foundationwizard.com.datagenerator.DataStructure
  helron.foundationwizard.com.datagenerator.DataStructureMapGenerator o-- helron.foundationwizard.com.datagenerator.DataStructureMap : dataStructureMap
  helron.foundationwizard.com.datagenerator.DataStructureMapGenerator o-- helron.foundationwizard.com.api.ApiStructuresExtractor : structures
  helron.foundationwizard.com.datagenerator.DataStructureStruct -up-|> helron.foundationwizard.com.datagenerator.DataStructureClass
  helron.foundationwizard.com.datagenerator.Parameter o-- helron.foundationwizard.com.datagenerator.ParamType : type
  helron.foundationwizard.com.ihm.FormField o-- helron.foundationwizard.com.ihm.FieldType : fieldType
  helron.foundationwizard.com.ihm.FormRequestDialog -up-|> javax.swing.JDialog
  helron.foundationwizard.com.ihm.FormRequestDialog o-- helron.foundationwizard.com.api.ApiStructuresExtractor : structures
  helron.foundationwizard.com.ihm.FormRequestDialog o-- helron.foundationwizard.com.ui.FormsContainer : tabsContainer
  helron.foundationwizard.com.ihm.FormRow -up-|> javax.swing.JPanel
  helron.foundationwizard.com.ihm.FoundationAPI o-- helron.foundationwizard.com.api.ApiStructuresExtractor : structures
  helron.foundationwizard.com.ihm.LuaScriptFrame -up-|> javax.swing.JFrame
  helron.foundationwizard.com.ihm.MainFrame -up-|> javax.swing.JFrame
  helron.foundationwizard.com.ui.FormCLass -up-|> javax.swing.JPanel
  helron.foundationwizard.com.ui.FormCLass o-- helron.foundationwizard.com.datagenerator.DataStructure : dataStructure
  helron.foundationwizard.com.ui.FormsContainer .up.|> helron.foundationwizard.com.ui.FormSelector
  helron.foundationwizard.com.ui.FormsContainer -up-|> javax.swing.JTabbedPane
  helron.foundationwizard.com.ui.FormsContainer o-- helron.foundationwizard.com.datagenerator.DataStructureMap : dataStructureMap
  helron.foundationwizard.com.ui.Home -up-|> javax.swing.JPanel
  helron.foundationwizard.com.ui.customcomponents.JImagePanel -up-|> javax.swing.JPanel
  helron.foundationwizard.com.ui.customcomponents.JTextFieldLink -up-|> javax.swing.JTextField
  helron.foundationwizard.com.ui.customcomponents.JtextFileChooser -up-|> javax.swing.JTextField
  helron.foundationwizard.com.ui.customcomponents.ListenedJCheckBox .up.|> java.awt.event.FocusListener
  helron.foundationwizard.com.ui.customcomponents.ListenedJCheckBox -up-|> javax.swing.JCheckBox
  helron.foundationwizard.com.ui.customcomponents.ListenedJCheckBox o-- helron.foundationwizard.com.ui.FormCLass : activeFormCLass
  helron.foundationwizard.com.ui.customcomponents.ListenedJComboBox .up.|> java.awt.event.FocusListener
  helron.foundationwizard.com.ui.customcomponents.ListenedJComboBox -up-|> javax.swing.JComboBox
  helron.foundationwizard.com.ui.customcomponents.ListenedJList -up-|> javax.swing.JList
  helron.foundationwizard.com.ui.customcomponents.ListenedJSpinner .up.|> javax.swing.event.ChangeListener
  helron.foundationwizard.com.ui.customcomponents.ListenedJSpinner -up-|> javax.swing.JSpinner
  helron.foundationwizard.com.ui.customcomponents.ListenedJSpinner o-- helron.foundationwizard.com.ui.FormCLass : activeFormCLass
  helron.foundationwizard.com.ui.customcomponents.ListenedTextField .up.|> java.awt.event.FocusListener
  helron.foundationwizard.com.ui.customcomponents.ListenedTextField -up-|> javax.swing.JTextField
  helron.foundationwizard.com.ui.customcomponents.PlusButton -up-|> javax.swing.JButton
  helron.foundationwizard.com.ui.customcomponents.PlusButton o-- helron.foundationwizard.com.datagenerator.ParamType : requestedFormType
  helron.foundationwizard.com.ui.customcomponents.ValidateButton -up-|> javax.swing.JButton
  helron.foundationwizard.com.ui.requests.RequestAssetType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestBooleanType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestClassType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestEnumType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestIntegerType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestListType .up.|> helron.foundationwizard.com.ui.requests.Requestable
  helron.foundationwizard.com.ui.requests.RequestStringType .up.|> helron.foundationwizard.com.ui.requests.Requestable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
