@startuml

title __API's Class Diagram__\n

    namespace elron.foundationWizzard.com {
      namespace api {
        class helron.foundationWizzard.com.api.ApiStructuresExtractor {
            - ASSET_PREFIX : String
            - CLASS_PREFIX : String
            - ENUM_PREFIX : String
            - STRUCTURE_PREFIX : String
            {static} - custom : Pattern
            {static} - dataIDExtractorFromParam : Pattern
            {static} - defaultValueMatcher : Pattern
            - dictionary : JsonElement
            - dictionaryAssetIndex : LinkedList<String>
            - dictionaryClassIndex : LinkedList<String>
            - dictionaryEnumIndex : LinkedList<String>
            - dictionaryIndex : LinkedList<String>
            - dictionaryStructIndex : LinkedList<String>
            + ApiStructuresExtractor()
            + EnumToList()
            + assetToList()
            + classToString()
            {static} + clean()
            {static} + cleanEnumTemplate()
            {static} + consoleDisplayLinkedMapToString()
            + entryList()
            + extractClass()
            + extractDataStructureAssetID()
            + extractDataStructureEnumID()
            + extractMatchTypeIndex()
            + extractParamDefaultValue()
            + extractParamType()
            + extractStructure()
            + extractTemplates()
            + extractWantedDataStructureId()
            + getASSET_PREFIX()
            + getCLASS_PREFIX()
            + getDictionaryAssetIndex()
            + getDictionaryClassIndex()
            + getDictionaryEnumIndex()
            + getDictionaryIndex()
            + getDictionaryStructIndex()
            + getENUM_PREFIX()
            + isAsset()
            + isClass()
            + isEnum()
            + isStruct()
        }
      }
    }

  


    namespace elron.foundationWizzard.com {
      namespace api {
        class helron.foundationWizzard.com.api.LuaGenerator {
            {static} - userInput : LinkedHashMap<String, String>
            + InitializeLuaTable()
            + LuaGenerator()
            + LuaGenerator()
            + buildLuaList()
            + buildLuaTable()
            {static} + main()
        }
      }
    }

  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
