@startuml

title __API's Class Diagram__\n

  namespace helron.foundationWizzard.com {
    namespace api {
      class helron.foundationWizzard.com.api.ApiStructuresExtractor {
          - ASSETPREFIX : String
          - CLASSPREFIX : String
          - ENUMPREFIX : String
          {static} - custom : Pattern
          {static} - defaultValueMatcher : Pattern
          - dictionary : JsonElement
          - dictionaryAssetIndex : LinkedList<String>
          - dictionaryClassIndex : LinkedList<String>
          - dictionaryEnumIndex : LinkedList<String>
          - dictionaryIndex : LinkedList<String>
          + ApiStructuresExtractor()
          + assetToList()
          + classToString()
          {static} + clean()
          {static} + cleanEnumTemplate()
          {static} + consoleDisplayLinkedMapToString()
          + entryList()
          + enumToList()
          + extractClass()
          + extractMatchTypeIndex()
          + extractParamDefaultValue()
          + extractParamType()
          + extractTemplates()
          + getDictionaryAssetIndex()
          + getDictionaryClassIndex()
          + getDictionaryEnumIndex()
          + getDictionaryIndex()
          + isAsset()
          + isEnum()
      }
    }
  }
  

  namespace helron.foundationWizzard.com {
    namespace api {
      class helron.foundationWizzard.com.api.LuaGenerator {
          {static} - userInput : LinkedHashMap<String, String>
          + InitializeLuaTable()
          + LuaGenerator()
          + buildLuaList()
          + buildLuaTable()
          {static} + main()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
