@startuml

title __REQUESTS's Class Diagram__\n


    namespace elron.foundationWizzard.com {
      namespace ui {
        namespace requests {
          class helron.foundationWizzard.com.ui.requests.RequestAssetType {
              + action()
              + isRequired()
          }
        }
      }
    }

  


    namespace elron.foundationWizzard.com {
      namespace ui {
        namespace requests {
          class helron.foundationWizzard.com.ui.requests.RequestBooleanType {
              + action()
              + isRequired()
          }
        }
      }
    }

  


    namespace elron.foundationWizzard.com {
      namespace ui {
        namespace requests {
          class helron.foundationWizzard.com.ui.requests.RequestClassType {
              + action()
              + isRequired()
          }
        }
      }
    }

  


    namespace elron.foundationWizzard.com {
      namespace ui {
        namespace requests {
          class helron.foundationWizzard.com.ui.requests.RequestEnumType {
              + action()
              + isRequired()
          }
        }
      }
    }

  


    namespace elron.foundationWizzard.com {
      namespace ui {
        namespace requests {
          class helron.foundationWizzard.com.ui.requests.RequestIntegerType {
              + action()
              + isRequired()
          }
        }
      }
    }

  


    namespace elron.foundationWizzard.com {
      namespace ui {
        namespace requests {
          class helron.foundationWizzard.com.ui.requests.RequestListType {
              + action()
              + isRequired()
          }
        }
      }
    }

  


    namespace elron.foundationWizzard.com {
      namespace ui {
        namespace requests {
          class helron.foundationWizzard.com.ui.requests.RequestStringType {
              + action()
              + isRequired()
          }
        }
      }
    }

  


    namespace elron.foundationWizzard.com {
      namespace ui {
        namespace requests {
          interface helron.foundationWizzard.com.ui.requests.Requestable {
              {abstract} + action()
              {abstract} + isRequired()
          }
        }
      }
    }

  


    namespace elron.foundationWizzard.com {
      namespace ui {
        namespace requests {
          class helron.foundationWizzard.com.ui.requests.RequestsGenerator {
              ~ requestsList : List<Requestable>
              + RequestsGenerator()
              + getRequestsList()
          }
        }
      }
    }

  

  helron.foundationWizzard.com.ui.requests.RequestAssetType .up.|> helron.foundationWizzard.com.ui.requests.Requestable
  helron.foundationWizzard.com.ui.requests.RequestBooleanType .up.|> helron.foundationWizzard.com.ui.requests.Requestable
  helron.foundationWizzard.com.ui.requests.RequestClassType .up.|> helron.foundationWizzard.com.ui.requests.Requestable
  helron.foundationWizzard.com.ui.requests.RequestEnumType .up.|> helron.foundationWizzard.com.ui.requests.Requestable
  helron.foundationWizzard.com.ui.requests.RequestIntegerType .up.|> helron.foundationWizzard.com.ui.requests.Requestable
  helron.foundationWizzard.com.ui.requests.RequestListType .up.|> helron.foundationWizzard.com.ui.requests.Requestable
  helron.foundationWizzard.com.ui.requests.RequestStringType .up.|> helron.foundationWizzard.com.ui.requests.Requestable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
